### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by juh2** [edhelas/atomtopubsub#8]
I try to post this Atom feed to Movim:
https://shaarli.hasecke.eu/?do=atom&searchtags=tango

And I get this error.

```
python atomtopubsub.py 
>> parsing tango
XML Error
>> create 
Fatal write error on socket transport
protocol: <publishx.Publishx object at 0x7f6488a89dd8>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Task exception was never retrieved
future: <Task finished coro=<parse() done, defined at atomtopubsub.py:28> exception=IqTimeout(<iq to="pubsub.movim.eu" id="e8aa14b9-5950-4fc8-9c11-990dba439b7c-1" type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub"><create node="tango" /><configure><x xmlns="jabber:x:data" type="submit"><field var="pubsub#persist_items"><value>1</value></field><field var="pubsub#title"><value /></field><field var="pubsub#max_items"><value>20</value></field><field var="pubsub#type"><value>http://www.w3.org/2005/Atom</value></field><field var="pubsub#deliver_payloads"><value>0</value></field><field var="pubsub#description"><value /></field></x></configure></pubsub></iq>,)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "atomtopubsub.py", line 44, in parse
    await xmpp.create(feed['server'], key, f.feed)
  File "/home/juh/Software/atomtopubsub/publishx.py", line 62, in create
    await task
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
slixmpp.exceptions.IqTimeout: <iq to="pubsub.movim.eu" id="e8aa14b9-5950-4fc8-9c11-990dba439b7c-1" type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub"><create node="tango" /><configure><x xmlns="jabber:x:data" type="submit"><field var="pubsub#persist_items"><value>1</value></field><field var="pubsub#title"><value /></field><field var="pubsub#max_items"><value>20</value></field><field var="pubsub#type"><value>http://www.w3.org/2005/Atom</value></field><field var="pubsub#deliver_payloads"><value>0</value></field><field var="pubsub#description"><value /></field></x></configure></pubsub></iq>

```

**Comment by edhelas** [comment]
Outdated, closing
